# Generated by Django 2.2.5 on 2019-09-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskBrowser',
            new_name='Task',
        ),
    ]
