# Generated by Django 2.2.5 on 2019-09-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20190923_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
