# Generated by Django 2.2.5 on 2019-09-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20190923_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
