# Generated by Django 2.2.5 on 2019-09-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20190923_2248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_id', 'parent')},
        ),
    ]
