# Generated by Django 2.1 on 2019-09-28 21:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0009_auto_20190924_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='task',
            name='lft',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='task',
            name='rght',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='task',
            name='tree_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('Sub Task', 'Sub Task')], max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='browser.Task'),
        ),
    ]
