# Generated by Django 2.1 on 2019-09-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0010_auto_20190928_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
