# Generated by Django 2.1 on 2019-09-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_auto_20190929_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
